apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: atum
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  # Ajuste storageClassName conforme o seu cluster
