apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: atum
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Ajuste storageClassName conforme o seu cluster:
  # storageClassName: standard        # GKE / minikube
  # storageClassName: gp2             # EKS
  # storageClassName: managed-premium # AKS
